pipeline:
    name: deploy-ecs-fargate
    identifier: deployecsfargate
    projectIdentifier: QuarkusRest
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: custom
              identifier: custcom
              description: ""
              type: Custom
              spec:
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: script 3
                                identifier: script_4
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "Hello"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: script 3
                                identifier: script_9
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "Hello"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - parallel:
                                - step:
                                      type: ShellScript
                                      name: script 3
                                      identifier: script_3
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo "Hello"
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                                - step:
                                      type: ShellScript
                                      name: Script 3
                                      identifier: Script_3
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: ls -lah
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
              tags: {}
        - stage:
              name: Build Project
              identifier: Build_Project
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: EKS
                          namespace: harness-ci
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushECR
                                name: quarkus-rest
                                identifier: quarkusrest
                                spec:
                                    connectorRef: AWS
                                    region: us-east-1
                                    account: "915632791698"
                                    imageName: quarkus-rest
                                    tags:
                                        - latest
    properties:
        ci:
            codebase:
                connectorRef: account.johnnorton
                repoName: quarkus-rest
                build: <+input>
