pipeline:
    name: deploy-ecs-fargate
    identifier: deployecsfargate
    projectIdentifier: QuarkusRest
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: custom
              identifier: custcom
              description: ""
              type: Custom
              spec:
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: Http
                                      name: harness
                                      identifier: harness
                                      spec:
                                          url: https://www.harness.io
                                          method: GET
                                          headers: []
                                          outputVariables: []
                                      timeout: 10s
                                - step:
                                      type: ShellScript
                                      name: Script 3
                                      identifier: Script_3
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: ls -lah
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                                - step:
                                      type: Http
                                      name: google
                                      identifier: google
                                      spec:
                                          url: https://www.google.com
                                          method: GET
                                          headers: []
                                          outputVariables: []
                                      timeout: 10s
                                      failureStrategies: []
                                - step:
                                      type: ShellScript
                                      name: Script 1
                                      identifier: Script_1
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: ls -la
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                                - step:
                                      type: ShellScript
                                      name: Script 2
                                      identifier: Script_2
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: ps -efx
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
              tags: {}
