pipeline:
    name: deploy-ecs-fargate
    identifier: deployecsfargate
    projectIdentifier: QuarkusRest
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: custom
              identifier: custcom
              description: ""
              type: Custom
              spec:
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: script 3
                                identifier: script_4
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "Hello"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: script 3
                                identifier: script_9
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "Hello"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - parallel:
                                - step:
                                      type: ShellScript
                                      name: script 3
                                      identifier: script_3
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo "Hello"
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                                - step:
                                      type: ShellScript
                                      name: Script 3
                                      identifier: Script_3
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: ls -lah
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
              tags: {}
