pipeline:
  name: Test3
  identifier: Test3
  projectIdentifier: GitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test stage
        identifier: test_stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 14m
        tags: {}
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  name: step123
                  identifier: step123
                  template:
                    templateRef: Template_Step_123
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.Local
              namespace: default
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build: <+input>
